
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import Logo from '@/common-components/header-components/Logo';
import { Box } from '@mui/material';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ToDo App',
  description: 'Generated by Akash',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <Box sx={{ marginLeft: 1 ,marginTop:1}}>
          <Logo />
        </Box> */}
        {children}
       
        </body>
    </html>
  )
}
